### ISSUE TITLE
Low means in cleaned data (cifti)

### ISSUE THREAD

**Issue by smeisler** [PennLINC/xcp_d#296]
Hello,

I am using XCP to clean cifti data output from fMRIPrep.
My 21.0.0 fMRIPrep extra arguments were `--use-syn-sdc --force-syn --cifti-output 91k --output-spaces MNI152NLin6Asym:res-2`. No errors to report.

My extra XCPD arguments are `--cifti -p acompcor_gsr --despike --motion-filter-type notch --band-stop-min 15 --band-stop-min 25 -f .9`.

I notice that the XCP_D outputs have very low means. I was wondering if this is expected. The low means are causing issues when I use XCP_D outputs on other software packages.

As an illustration, here are the fmriprep vs xcp outputs, with mean signal plotted on the right hemisphere:
<img width="361" alt="image" src="https://user-images.githubusercontent.com/27028726/153680697-9e8c5fd6-aa23-4765-85cd-9baddb4bb09a.png">

Thanks,
Steven

**Comment by shaohanyu2017** [comment]
I used xcp_d to denoise task fmri. I encountered the same issue after running --input-type fmriprep --smoothing 6 --despike -p acompcor --lower-bpf 0.01 --upper-bpf 0.15.  The residual timecourse obtained could not be properly processed by fsl. The values are very low. I tried to add the mean_func to the residual timecourse in order to let fsl work normally, but I think it might affect the statistic result.

**Comment by mb3152** [comment]
@smeisler can you post your data so I can test it out?

**Comment by smeisler** [comment]
Sure, an example fMRIPrep subject output may be found here: https://drive.google.com/file/d/169bmXHm8HgwoBPEZG7wJRupDeWmrecb-/view?usp=sharing
(it is from an openneuro dataset so I am not too concerned about posting processed derivatives publicly)

Thanks for investigating!

Steven

**Comment by mb3152** [comment]
Okay, @a3sha2 explained that we can add the mean back after filtering. This has been implemented in the latest repo. Thanks for bringing this to our attention.

**Comment by smeisler** [comment]
Thanks! I will check it out later this week.
