### ISSUE TITLE
xcp_d.utils.bids.BIDSERROR BIDS root folder ... could not find participants. BIDS Validator Error despite no edits to fmriprep output. 

### ISSUE THREAD

**Issue by keithcdodd** [PennLINC/xcp_d#342]
Hello, I am running into errors running Docker xcp_d despite troubleshooting.

It says on the documentation to give xcp_d the outputs from fmriprep. Yet, it appears the error appears because xcp-d then tries to run bids validator on fmriprep output, but it is not valid. Sure enough, putting any fmriprep data output folder that I have does not validate with BIDS. I am unsure how to proceed. This is simply the output data from a successful fmriprep run, which is not bids compatible, although the original input data into fmriprep is BIDS compatible and I have not edited the fmriprep output in any way.

What am I missing? Thank you!

Here is what I am running for reference:
`docker run --rm -it \
  -v ${preproc} \
  -v ${preproc}/derivatives/fmriprep \
  -v ${preproc}/derivatives \
  -v /tmp/wkdir:/wkdir \
  -v /tmp:/scrth \
  -v /tmp/xcpd_ciftiF/:/out \
  pennlinc/xcp_d:latest \
  ${preproc}/derivatives/fmriprep ${preproc}/derivatives/xcp_d \
  --participant_label ${l} -t ${taskid} -d 4 -p aroma --band-stop-min 12 --band-stop-max 28  -w /wkdir`

**Comment by shuerye** [comment]
Hi, the same problem happened to me as well, and cannot find a solution so far.  When I run the XCP-D code, my data failed BIDS validation with the No Valid Data Found and Not Included errors.  

A thread under fmriprep topic suggested that the output of fmriprep didn't fit BIDS (https://github.com/nipreps/fmriprep/issues/1888), therefore the output cannot pass the mandatory BIDS validation. The problem may due to the connection problem of fmriprep and XCP-D. Since the XCP-D directly consumes the outputs of fmriprep, I think it can be solved in an elegant manner, but I can't get farther and really need help from developers.

Thanks in advance! 

There is the code:
`sudo docker run --rm -it -v /fmriprep_output:/OutputMovie:ro -v /xcp_d:/wrdir -v /xcp_d/tmp:/work pennlinc/xcp_d:latest /fmriprep_output/OutputMovie participant --participant_label 251 -v -d 4.8 --despike --smoothing 4 --upper-bpf 0.1 --lower-bpf 0.01 --input-type fmirprep`

**Comment by kahinimehta** [comment]
Hi! XCP doesn't actually do any BIDS validation - we will be editing the error message for clarity!

In the mean time, could you confirm that you are pointing XCP to a folder that has a "derivatives" sub-folder in it, which has the fmriprep outputs (i.e: the sub-*/ses-*/* folder)?

**Comment by shuerye** [comment]
Thank you for your attention.  I was using the latest version of pennlinc/xcp_d. The error is presented as follows:
```
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 400, in build_workflow
    layout = BIDSLayout(str(fmri_dir),validate=False, derivatives=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/layout.py", line 126, in __init__
    root, description = validate_root(root, validate)
  File "/usr/local/miniconda/lib/python3.8/site-packages/bids/layout/validation.py", line 68, in validate_root
    raise ValueError("BIDS root does not exist: %s" % root)
ValueError: BIDS root does not exist: /fmriprep_output/OutputMovie
```

1.  I have the dataset_description.json in my output directory.  The content are as follows: 
{
    "Name": "fMRIPrep - fMRI PREProcessing workflow",
    "BIDSVersion": "1.4.0",
    "DatasetType": "derivative",
    "GeneratedBy": [
        {
            "Name": "fMRIPrep",
            "Version": "21.0.1",
            "CodeURL": "https://github.com/nipreps/fmriprep/archive/21.0.1.tar.gz"
        }
    ],
    "HowToAcknowledge": "Please cite our paper (https://doi.org/10.1038/s41592-018-0235-4), and include the generated citation boilerplate within the Methods section of the text."
}

2. The data structure is:

OutputMovie
├── logs
├── sourcedata
│    └──freesurfer
├── sub-055
│    ├── anat
│    ├── figures
│    ├── fmap
│    ├── func
│    └── log
├── sub-251
│     ├── anat
│     ├── figures
│     ├── fmap
│     ├── func
│     └── log
├── .bidsignore
├── dataset_description.json
├── desc-aparcaseg_dseg.tsv
├── desc-aseg_dseg.tsv
├── sub-055.html
└── sub-251.html

 3. The data is pilot and has not been made public。


 Thank you!

**Comment by kahinimehta** [comment]
Hello @shuerye! We were able to reproduce your error locally, but when we adjusted our call it seems to run! Let us know if this works for you, if not we are always happy to troubleshoot further:

`sudo docker run --rm -it  -v /FULL PATH TO FMRIPREP OUTPUT FOLDER:/in/ -v /FULL PATH TO DESIRED XCP OUTPUT FOLDER:/out/ -v /FULL PATH TO DESIRED WORKING DIRECTORY:/work/ pennlinc/xcp_d:latest  /in/ /out/ --participant_label colornest001 -v -d 4.8 --despike --smoothing 4 --upper-bpf 0.1 --lower-bpf 0.01`


Additionally, we are pushing a new 'latest' tagged image (v0.1.2) that has some fixes, and should be out in the next couple of hours - I would recommend using that image! Thanks again for your patience.

**Comment by shuerye** [comment]
Thanks for your quick respose. I used the new call in the new version 0.1.2 and it looks good, but still reported errors as follow:

`Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/cli/run.py", line 526, in build_workflow
    subject_list = collect_participants(
  File "/usr/local/miniconda/lib/python3.8/site-packages/xcp_d/utils/bids.py", line 108, in collect_participants
    raise BIDSError(
xcp_d.utils.bids.BIDSError:
---------- BIDS root folder: "BIDS Layout: .../in | Subjects: 0 | Sessions: 0 | Runs: 0" ----------
           Could not find participants. Please make sure the BIDS derivatives are accessible to Docker/ are in BIDS directory structure.`

Should I change my directory structure which is the original fmriprep output? Since the output (BIDS derivatives) does not pass the online BIDS validation with NO_VALID_DATA_FOUND_FOR_SUBJECT error.

 I'd really appreciate it if you could provide any thoughts.

**Comment by kahinimehta** [comment]
Hello @shuerye , thanks for letting me know! If the BIDS validator cannot find valid data, it's possible that this is the issue (since XCP does use a BIDSLayout object, even if it doesn't run the validator).

It might be worth re-organizing the 'OutputMovie' directory - while I can't guarantee this will work, the most immediate thing I can think of is moving things around so only the subject directories and .htmls (i.e, sub-251 and sub-055) and dataset_description.json are in the OutputMovie folder:

```
OutputMovie
|------sub-055(directory)
|------sub-251(directory)
|------sub-055.html
|------sub-251.html
|------dataset_description.json
```

 Checking the .bidsignore might also be worth a try!
