### ISSUE TITLE
Consolidate multiple functions in utils/confounds.py into one

### ISSUE THREAD

**Issue by kahinimehta** [PennLINC/xcp_d#676]
Consolidate functions in utils/confounds.py into one function as described in https://github.com/PennLINC/xcp_d/pull/675#discussion_r1026918828.

**Comment by tsalo** [comment]
>Given that this no longer uses the confounds file, I think we should (1) use this function to select the confounds file, rather than anything earlier in the workflow and (2) use this function to load the necessary motion parameters for CensorScrub, probably in a separate file.

**Comment by tsalo** [comment]
Hopefully we can (1) find the custom confounds file, (2) select confounds based on the nuisance strategy, (3) consolidate the confounds, and (4) load/filter the motion parameters in one step.

**Comment by tsalo** [comment]
The step that finds the custom confounds file needs to be a regular function, so we can incorporate that information into the boilerplate, so that can't be merged into an interface.

Confound selection and confound consolidation currently happens in a node function, which could be converted to an interface.

Motion filtering happens in the FlagMotionOutliers interface. I don't think it's worth it to combine that with confound consolidation though.

**Comment by tsalo** [comment]
I'mfind with the code as-is now.
