### ISSUE TITLE
execsummary.py using freesurfer output in 'derivatives' rather than 'fmriprep/sourcedata'

### ISSUE THREAD

**Issue by Bramdiamond** [PennLINC/xcp_d#707]
execsummary.py will use the first freesurfer directory it finds in the derivatives directory. If none exist, it will search in the fmriprep directory. This is an issue because:
1. There may be ≥ 2 freesurfer versions in the derivatives directory (e.g., 'freesurfer_v53' & 'freesurfer_v72') & no output from fmriprep; in which case the used should specify which version is used.
2. There may be ≥ 1 freesurfer versions in the derivatives directory &  freesurfer output from fmriprep; in which case the default should be fmriprep output.

This is my first Bug report. Please excuse any etiquette mistakes.

**Comment by tsalo** [comment]
Thank you for opening this @Bramdiamond.

>1. There may be ≥ 2 freesurfer versions in the derivatives directory (e.g., 'freesurfer_v53' & 'freesurfer_v72') & no output from fmriprep; in which case the used should specify which version is used.

We don't currently have a mechanism in xcp-d to support this, although Docker and Singularity users could mount the FreeSurfer directory with xcp-d's search method in mind. Alternatively, we could maybe look for an environment variable that users could set when they call xcp-d? Something like SUBJECTS_DIR, maybe. WDYT?

>2. There may be ≥ 1 freesurfer versions in the derivatives directory & freesurfer output from fmriprep; in which case the default should be fmriprep output.

Agreed. I'm planning to change how we identify the FreeSurfer directory, so that it looks in `sourcedata/` first (i.e., how fMRIPrep versions >= 20.2.1 organize FreeSurfer derivatives), and then looks in the parent directory if that's unavailable.

**Comment by Bramdiamond** [comment]
I symlinked the intended freesurfer directory to my derivatives folder as 'freesurfer', which did the trick. 

1. I think an fs-directory flag would be more user friendly. $SUBJECTS_DIR is set to $FREESURFER_HOME/subjects by default. Many users may forget this and xcp-d will fail. IMHO, the current set-up is better than defaulting to $SUBJECTS_DIR.
2.  Looking forward to this update!

**Comment by tsalo** [comment]
I think a fs-directory flag might be overkill, given that this should only impact users who (1) are using old versions of fMRIPrep and (2) ran multiple versions of FreeSurfer in the same derivatives directory. I agree with your point about SUBJECTS_DIR, so what I can do instead is raise an exception if multiple FreeSurfer folders are found, and include a _very_ informative error message.
