### ISSUE TITLE
XCP-D version for task data processing

### ISSUE THREAD

**Issue by moser297** [PennLINC/xcp_d#775]
I'm currently working on analyzing infant task data with the Nibabies + XCP-D workflow. It would be amazing, if XCP-D would  have a flag to skip the regression step as this is something that's not recommended to do before running a GLM. It could be a flag to basically skip all the data cleaning steps (regression, filtering) but still transfer the data into the appropriate cifti space and output the motion parameters. 
I would be happy to hear your suggestions for the implementation of this and I'm happy to help if I can.

**Comment by tsalo** [comment]
Can you expand on which XCP-D derivatives you want?

**Comment by moser297** [comment]
I would love to have all anatomical XCP-D derivatives and a not denoised version of the dtseries for each run (I assume a concatenated version would be challenging without denoising?) plus the motion outputs.

**Comment by tsalo** [comment]
@moser297 we're making slow progress on this. I have opened a separate issue to support a "none" option for the nuisance regression. Also, we are working on support just high-pass or low-pass filters, rather than just a bandpass filter, which should work better with task data.

I'm less sure about extracting nuisance regressors or motion parameters from the preprocessing derivatives when XCP-D won't be doing any denoising or censoring. I think outputting the filtered FD makes sense, but not a list of outliers or nuisance regressors from a given strategy. Happy to discuss it though.
