### ISSUE TITLE
Include HCPex in XCP-D

### ISSUE THREAD

**Issue by andreifoldes** [PennLINC/xcp_d#939]
## Summary
I think it would be very useful to have an atlas that includes both cortical and subcortical parcellations. I personally would be very interested in having HCPex included specifically: 
 - https://link.springer.com/article/10.1007/s00429-021-02421-6
 - https://github.com/wayalan/HCPex

## Additional details
- appears to have a wider subcortical coverage than Tian atlas
- includes the HCP-MMP v1.0, Glasser et al. 2016 that users are already familiar with

**Comment by tsalo** [comment]
We currently have both the Glasser and the HCP subcortical atlases in XCP-D, so if the HCP subcortical atlas is equivalent to the subcortical portion of HCPex, then you could concatenate the time series files and calculate the correlation coefficients. 

If the subcortical atlases are equivalent, then I'd be happy to swap out the Glasser and HCP atlases for the HCPex. If they are different, then I would be willing to swap out just the Glasser for HCPex, as long as the labels are synchronized (e.g., if HCPex uses different labels for the same regions, then I'd need the Glasser names also included in the label TSV file).

In either case, I would need an fsLR-space CIFTI version of HCPex in order to add it to XCP-D, and I don't see one in the repo you linked. Any chance you could hunt a CIFTI version down?

By the way, we do have a set of atlases with both cortical and subcortical regions, as of two days ago. We're calling these atlases "4S", as they're the Schaefer cortical atlases combined with the Diedrichson cerebellar atlas, the CIT168 subcortical atlas, and a thalamic atlas.

**Comment by andreifoldes** [comment]
> We currently have both the Glasser and the HCP subcortical atlases in XCP-D, so if the HCP subcortical atlas is equivalent to the subcortical portion of HCPex, then you could concatenate the time series files and calculate the correlation coefficients.

I believe that the HCP subcortical atlases has 19 nodes, whereas HCPex has 66.

> If the subcortical atlases are equivalent, then I'd be happy to swap out the Glasser and HCP atlases for the HCPex. If they are different, then I would be willing to swap out just the Glasser for HCPex, as long as the labels are synchronized (e.g., if HCPex uses different labels for the same regions, then I'd need the Glasser names also included in the label TSV file).

Yes, that makes sense, the idea being that an HCPex CIFTI would have the equivalent cortical nodes as the Glasser atlas coupled with a more extensive subcortical parcellation.

> In either case, I would need an fsLR-space CIFTI version of HCPex in order to add it to XCP-D, and I don't see one in the repo you linked. Any chance you could hunt a CIFTI version down?

Yes I have begun the hunt (contacted the first author via email). I'm also exploring the possibility of swapping out the subcortical part of the HCPex with the subcortical part of the HCP standard (see end of this thread: https://groups.google.com/a/humanconnectome.org/g/hcp-users/c/IB-E8eTSxOg/m/JnOA4F96AAAJ). If I understand correctly the only "serious" transformation with this approach will involve going from "MNI152 ICBM 2009c asymmetric" to "MNI152NLin6" and then using `wb_command -cifti-replace-structure`. Do you think this is still a viable route?

> By the way, we do have a set of atlases with both cortical and subcortical regions, as of two days ago. We're calling these atlases "4S", as they're the Schaefer cortical atlases combined with the Diedrichson cerebellar atlas, the CIT168 subcortical atlas, and a thalamic atlas.

That's amazing news as I was looking for atlases that include the VTA which I know see the CIT168 does. I was looking in the "atlas" directory, but couldn't find this new "4S" atlas. Is there a dev version of xcp_d I could take for a spin to see the coverage of this new atlas on my dataset?

Relatedly are the any plans for extending XCP_D to additionally work with custom CIFTI atlases?

**Comment by andreifoldes** [comment]
> You can download the atlases from [PennLINC/AtlasPack](https://github.com/PennLINC/AtlasPack) or run the unstable XCP-D Docker image on your data to see how they look.

I had a look today at the new 4S* atlases! Very cool idea, but I can't help but ask whether there is any possibility to complement it with a hippocampal node? ^^

**Comment by tsalo** [comment]
>Or should one just combine the Tian with the CIT168 in post-processing?

That's definitely doable.

>I can't help but ask whether there is any possibility to complement it with a hippocampal node?

Do you have a preferred hippocampal atlas?

**Comment by andreifoldes** [comment]
Perhaps the HCPs hippocampus? I saw ThalamusHCP so I guess that would provide some consistency.

**Comment by tsalo** [comment]
Can you share a link to that atlas?

**Comment by andreifoldes** [comment]
Sure - I was thinking of this one: https://github.com/PennLINC/xcp_d/blob/main/xcp_d/data/atlases/atlas-HCP_dseg.tsv

**Comment by tsalo** [comment]
We added hippocampus and amygdala nodes to the 4S atlases, so I think we can close this now.
