### ISSUE TITLE
Cubic spline interpolation at beginning/end of scan + bandpass filtering causes artifacts

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d#949]
## Summary

This stems from https://neurostars.org/t/odd-xcp-d-denoised-timeseries/26559.

The gist seems to be that cubic spline interpolation + Butterworth bandpass filtering can lead to weird spikes at the beginning/end of the scan (similar to what happens when you do filtering without padding, weirdly) when the interpolated volumes are at the beginning/end of the scan.

This bug affects versions 0.4.0rc2 - 0.5.0.

## Additional details

- xcp_d version: 0.4.0
- Docker version:
- Singularity version:

### What were you trying to do?

Visualize parcellated time series.

### What did you expect to happen?

For the time series to look fairly consistent in terms of scale across the whole run.

### What actually happened?

The time series jumps in scale at the beginning or end of the run.

## Reproducing the bug

I'm thinking of maybe setting the motion parameters to high values at the beginning/end of a test run and then running XCP-D.

**Comment by jhuguetn** [comment]
The signal interpolation in the XCP-D bandpass filtering step gives bad results when there are censored volumes either at the beginning or end of the timeseries (even if there’s only one single volume).  
The source of that problem derives from having a Spline interpolation were the method is asked to _predict values_ outside the range of data available (instead of finding intermediate values within as expected). That is, _extrapolating_. 

XCP-D calls nilearn's [_interpolate_volumes()](https://github.com/nilearn/nilearn/blob/b1fa2e0b9161a5055a900b708aed38aaab15866f/nilearn/signal.py#L779) internal function, which uses scipy [scipy.interpolate.CubicSpline](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.CubicSpline.html#scipy.interpolate.CubicSpline) class for the interpolation process.   
`CubicSpline` class has a `extrapolate` boolean flag to enable/disable interpolation in those cases (both ends of the range of data) which is set to True by default. `CubicSpline` class initialization at `_interpolate_volumes()` enables therefore extrapolation without exposing the class parameter (so it cannot be switched), which leads to the reported problem. 

Follow issue opened at nilearn: https://github.com/nilearn/nilearn/issues/4024
